### PR TITLE
Update CHARMM energy comparison script for py3 compatibility

### PR DESCRIPTION
**Pull request by jchodera**
This fixes a py3 incompatible use of `subprocess.check_output()`.

### CODE REVIEW

**Comment by swails** [comment]
Where should this repo live? Is it still useful?

Keeping it under my account is a recipe for neglect and decay.

**Comment by jchodera** [comment]
Transfer it to choderalab? I can give @peastman write access too.

**Comment by swails** [comment]
choderalab or pandegroup are both fine. 

What do you think, @peastman?

**Comment by peastman** [comment]
That's fine with me.  I hadn't even known this repository existed.

**Comment by swails** [comment]
You did at one point. I think this was to put the energy comparison scripts we made for the paper in an accessible place so others could reproduce our results.

**Comment by jchodera** [comment]
I'd love to update/extend this for the 7.2 upcoming release too.

**Comment by jchodera** [comment]
Could we transfer this to `choderalab` for now then? After I get it cleaned up, we can transfer it to wherever @peastman wants.

**Comment by swails** [comment]
choderalab/OpenMMEnergyComparisons already exists and You don’t have the permission to create repositories on choderalab

**Comment by jchodera** [comment]
Whoops!

`choderalab/OpenMMEnergyComparisons` has been deleted and you've been invited to be a member of `choderalab`.

Thanks!

**Pull request merged**
